# Generated by Django 6.1.1 on 2026-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_enrollment_number', models.CharField(max_length=20, unique=True)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phone_number', models.IntegerField(max_length=15)),
                ('s_course', models.CharField(max_length=100)),
                ('s_year', models.IntegerField()),
                ('s_date_of_admission', models.DateField()),
            ],
        ),
    ]
