# Generated by Django 6.1.1 on 2026-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_duration', models.IntegerField()),
                ('c_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trainer_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
    ]
