# Generated by Django 6.1.1 on 2026-09-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_brand', models.CharField(max_length=100)),
                ('p_model', models.CharField(max_length=100)),
                ('p_warranty', models.IntegerField(help_text='Warranty period in months')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_code', models.CharField(max_length=100, unique=True)),
                ('p_category', models.CharField(max_length=100)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_stockquantity', models.IntegerField()),
                ('p_description', models.TextField()),
                ('p_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
