# Generated by Django 6.1.1 on 2026-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_id', models.CharField(max_length=50, unique=True)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_department', models.CharField(max_length=100)),
                ('e_job_role', models.CharField(max_length=100)),
                ('e_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_date_of_joining', models.DateField()),
            ],
        ),
    ]
